src/accueil/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	accueil_details,
	)

urlpatterns = [
	url(r'^$', accueil_details, name='acceuil'),
]

src/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
   
    url(r'^$', include("accueil.urls", namespace='index')),

    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^blogue/', include("blogue.urls", namespace='blogue')),
    url(r'^contact/', include("contact.urls", namespace='contact')),
    url(r'^entreprise/', include("entreprise.urls", namespace='entreprise')),
    url(r'^services/', include("services.urls", namespace='services')),
    url(r'^accompagnement-personnalise/', include("coaching.urls", namespace='coaching')),
 
    


    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^posts/', include("posts.urls", namespace='posts')),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blogue/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	blogue_list,
	blogue_details,
	)

urlpatterns = [
	url(r'^$', blogue_list, name='liste'),
	url(r'^article$', blogue_details, name='details'),
]

src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/services/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	service_liste,
	service_audit_web,
	service_seo,
	service_medias_sociaux,
	service_courriels,
	service_developpement_web,
	service_cms
	)

urlpatterns = [
	url(r'^$', service_liste, name='liste'),
	url(r'audit-web/$', service_audit_web, name='audit_web'),
	url(r'seo/$', service_seo, name='seo'),
	url(r'medias-sociaux/$', service_medias_sociaux, name='medias_sociaux'),
	url(r'campagne-courriel/$', service_courriels, name='courriels'),
	url(r'developpement-web/$', service_developpement_web, name='developpement_web'),
	url(r'plateforme-gestion-de-contenu/$', service_cms, name='cms'),
]

src/posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify


from markdown_deux import markdown
from comments.models import Comment

from .utils import get_read_time
# Create your models here.
# MVC MODEL VIEW CONTROLLER


#Post.objects.all()
#Post.objects.create(user=user, title="Some time")

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            width_field="width_field", 
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time =  models.IntegerField(default=0) # models.TimeField(null=True, blank=True) #assume minutes
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

src/posts/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except: 
    pass

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post



def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
		
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		# message success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)

def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	if instance.publish > timezone.now().date() or instance.draft:
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	share_string = quote_plus(instance.content)

	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id
	}
	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid() and request.user.is_authenticated():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get('object_id')
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()


		new_comment, created = Comment.objects.get_or_create(
							user = request.user,
							content_type= content_type,
							object_id = obj_id,
							content = content_data,
							parent = parent_obj,
						)
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())


	comments = instance.comments
	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"comments": comments,
		"comment_form":form,
	}
	return render(request, "post_detail.html", context)

def post_list(request):
	today = timezone.now().date()
	queryset_list = Post.objects.active() #.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()
	
	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 8) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"object_list": queryset, 
		"title": "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "post_list.html", context)





def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "post_form.html", context)



def post_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfully deleted")
	return redirect("posts:list")

src/templates/calltoaction.html
    <section class="row trial30_banner">
        <div class="container">
            <div class="row">
                <div class="col-sm-10">
                    <div class="row">
                        <h2>Augmentez votre présence numérique!</h2>
                        <h5>Optimisez votre site, augmentez votre visibiliter dans les moteurs de recherche, augmentez vos ventes, maintenant!</h5>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="row">
                        <a href="{% url "contact:details" %}" class="borderred_link"><span>Nous contacter</span></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

src/templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}

<div class='col-sm-6 col-sm-offset-3'>
  <h1>Confirm Delete</h1>
        
      
            <form method="POST" action="."> {% csrf_token %}
                <p>A re you sure you want to delete: "{{ object.content }}"?</p>
              
                <input type='submit' value='Confirm' class='btn btn-warning'>
                <a href='{{ object.get_absolute_url }}' class='btn btn-default'>Cancel</a>
            </form>
        </div>

    

        <hr/>
</div>


{% endblock content %}

src/templates/counter.html
       <div class="row m0 funfacts_ab">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3 fact">
                        <div class="row">
                            <h3><span class="counter">100</span>%</h3>
                            <h5>Clients satisfaits</h5>
                        </div>
                    </div> <!--Fact-->
                    <div class="col-sm-3 fact">
                        <div class="row">
                            <h3><span class="counter">2</span></h3>
                            <h5>années de service</h5>
                        </div>
                    </div> <!--Fact-->
                    <div class="col-sm-3 fact">
                        <div class="row">
                            <h3>+ <span class="counter">300</span></h3>
                            <h5>heures de formation</h5>
                        </div>
                    </div> <!--Fact-->
                    <div class="col-sm-3 fact">
                        <div class="row">
                            <h3>+ <span class="counter">4000</span></h3>
                            <h5>heures de programmation</h5>
                        </div>
                    </div> <!--Fact-->
                </div>
            </div>
        </div>

src/templates/couverture.html
<section class="row pageCover">
    <div class="container p0">
        <h3 class="fleft">{{ title }}</h3>
        <ol class="breadcrumb">
            <li><a href="{% url 'index:acceuil' %}">Accueil</a></li>
            {% if page_active and lvl3 %}
                <li> <a href="{% url 'services:liste' %}">{{ page_active }}</a></li>
            {% endif %}
             {% if page_active and not lvl3 %}
                <li class="active">{{ page_active }}</li>
            {% endif %}
            {% if lvl3 %}
                <li class="active">{{ title }}</li>
            {% endif %}


        </ol>
    </div>
</section>

src/templates/footer.html
{% load staticfiles %}
   <footer class="row">
        <div class="row m0 top_footer">
            <div class="container">
                <div class="row footer_widgets">
                    <div class="col-sm-4 footer_widget">
                        <div class="row m0">
                            <h4 class="title">À propos de nous</h4>
                            <div class="row m0 body">
                                <p>Conseil Stratégique Marketing Web est une entreprise spécialisée dans le marketing web et les stratégies de SEO. CSM pratique principalement dans l'Est du Québec. Son objectif principal est d'aider les PME et les organismes en région à garantir leur place sur le Web et ainsi assurer la longétivé de leurs services en région.
                                <a href="#" class="borderred_link"><span>Nous contacter</span></a></p>

 <!--                               <ul class="nav socials">
                                     <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                    <li><a href="#"><i class="fa fa-rss"></i></a></li>
                                </ul> -->
                            </div>
                        </div>
                    </div> <!--Single widget-->
                    <div class="col-sm-4 footer_widget">
                        <div class="row m0">
                            <h4 class="title">Service offerts</h4>
                            <div class="row m0 body">
                                <ul class="list-unstyled links">
                                    <li class="fa fa-caret-right"><a href="{% url "services:audit_web" %}">Audit web</a></li>
                                    <li class="fa fa-caret-right"><a href="{% url "services:seo" %}">Services SEO</a></li>
                                    <li class="fa fa-caret-right"><a href="{% url "services:medias_sociaux" %}">Médias sociaux</a></li>
                                    
                                    <li class="fa fa-caret-right"><a href="{% url "services:developpement_web" %}">Développement Web</a></li>
                                    <li class="fa fa-caret-right"><a href="{% url "services:courriels" %}">Campagne courriels & promotion</a></li>
                                    <li class="fa fa-caret-right"><a href="{% url "services:cms" %}">Plateforme de gestion de contenu</a></li>


                                </ul>
                            </div>
                        </div>
                    </div> <!--Single widget-->
                    <div class="col-sm-4 footer_widget">
                        <div class="row m0">
                            <h4 class="title">Derniers articles du blogue</h4>
                            <div class="row m0 body">
                                <!-- Begin MailChimp Signup Form -->
                                <div id="mc_embed_signup" class="row m0">
                                    <form 
                                      action="" 
                                       id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" 
                                      class="validate mailchimp_form" target="_blank">
                                        <div id="mc_embed_signup_scroll">                                            
                                            <div class="mc-field-group input-group ">
                                                <span class=""><img src='{% static "images/icons/footer/name.png" %}' alt=""></span>
                                                <span class="email"><a href="">01/01/2001 - Titre de l'article</a></span>
                                            </div>
                                            <div class="mc-field-group input-group ">
                                                <span class=""><img src='{% static "images/icons/footer/name.png" %}' alt=""></span>
                                                <span class="email"><a href="">01/01/2001 - Titre de l'article</a></span>
                                            </div>
                                            <div class="mc-field-group input-group ">
                                                <span class=""><img src='{% static "images/icons/footer/name.png" %}' alt=""></span>
                                                <span class="email"><a href="">01/01/2001 - Titre de l'article</a></span>
                                            </div>
                                            <div class="clear">
                                                <button type="submit" name="subscribe" id="mc-embedded-subscribe" class="button btn submit_btn borderred_link"><span>Voir tous les articles</span></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <!--End mc_embed_signup-->
                            </div>
                        </div>
                    </div> <!--Single widget-->
                </div>
                </div>
                <div class="container-fuild">
                
                <div class="row footer_widgets2 m0">
                   <div class="container"> <ul class="nav nav-justified">
                        <li>
                            <a href="#">
                                <img src='{% static "images/icons/footer/call.png" %}' alt=""><strong>Nous appeler</strong>: (581) 624-1766
                            </a>
                        </li>
                        <li>

                        </li>
                        <li>
                            <a href="mailto:cotecsm@globetrotter.net">                                
                                <img src='{% static "images/icons/footer/mail.png" %}' alt=""><strong>Courriel</strong>: cotecsm@globetrotter.net
                            </a>
                        </li>
                    </ul>
                </div>
                </div>

                </div>
            </div>
        </div>
        <div class="row copyright m0 ">Copyright &copy; 2016 <a href="http://epokeweb.com">EpokeWeb</a>. Tous droits réservés.</div>
    </footer>

src/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}

src/templates/javascript.html
{% load staticfiles %}
   <!--jQuery, Bootstrap and other vendor JS-->
    
    <!--jQuery-->
    <script src='{% static "js/jquery-2.1.3.min.js" %}'></script>
    
    <!--Bootstrap JS-->
    <script src='{% static "js/bootstrap.min.js" %}'></script>
    
    <!--Owl Carousel-->
    <script src='{% static "vendors/owl.carousel/js/owl.carousel.min.js" %}'></script>
    
    <!--Bootstrap Select-->
    <script src='{% static "vendors/bootstrap-select/js/bootstrap-select.min.js" %}'></script>
    
    <!--FlexSlider-->
    <script src='{% static "vendors/flexslider/jquery.flexslider-min.js" %}'></script>
    
    <!--Counter Up-->
    <script src='{% static "vendors/counterup/jquery.counterup.min.js" %}'></script>
    
    <!--Waypoints-->
    <script src='{% static "vendors/waypoints/waypoints.min.js" %}'></script>
    
    <!--RV-->
    <script src='{% static "vendors/rs-plugin/js/jquery.themepunch.tools.min.js" %}'></script>
    <script src='{% static "vendors/rs-plugin/js/jquery.themepunch.revolution.min.js" %}'></script>
    
    <!--Mailchimp -->
<script src='{% static "js/mc-validate.js" %}'></script>
<script>
(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[1]='FNAME';ftypes[1]='text';fnames[0]='EMAIL';ftypes[0]='email';fnames[2]='MMERGE2';ftypes[2]='url';}(jQuery));var $mcj = jQuery.noConflict(true)
</script> 
    
    <!--Strella JS-->
    <script src='{% static "js/theme.js" %}'></script>
    <script src='{% static "js/revs.js" %}'></script>


<script type="text/javascript">
$(document).ready(function(){
    $(".content-markdown").each(function(){
            var content = $(this).text()
            var markedContent = marked(content)
            $(this).html(markedContent)
    })
    $(".post-detail-item img").each(function(){
            $(this).addClass("img-responsive");
    })


    var contentInput = $("#id_content");

    function setContent(value){
        var markedContent = marked(value)
        $("#preview-content").html(markedContent)
        $("#preview-content img").each(function(){
            $(this).addClass("img-responsive")
        })
    }
    setContent(contentInput.val())

    contentInput.keyup(function(){
        var newContent = $(this).val()
        setContent(newContent)
    })

    var titleInput = $("#id_title");
    


    function setTitle(value) {
        $("#preview-title").text(value)
    }
    setTitle(titleInput.val())

    titleInput.keyup(function(){
        var newContent = $(this).val()
        setTitle(newContent)
    })

    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
    })


    // preview-title
    // preview-content

})

</script>

src/templates/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

src/templates/navbar.html
{% load staticfiles %}
    <header class="row">
        <div class="top_row row m0">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 tagLine hidden-xs">
                        <i class="fa fa-line-chart"></i> CSM - Pour vos besoins en analyse et développement web 
                    </div>


                    <div class="col-sm-6">
                        <ul class="nav navbar-right  ">
                            {% if not request.user.is_authenticated %}
                                <li class="text-xs-center">
                                    <a href="#"><img src='{% static "images/icons/top-bar/user.png" %}' alt="">Connexion / Inscription</a>
                                </li>
                            {% else %}
                                <li class="text-xs-center">
                                    <a href="{% url 'logout' %}"><img src='{% static "images/icons/top-bar/user.png" %}' alt="">Déconnexion</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!--Top Row-->
        <div class="logo_row row m0">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <a class="logo" href="{% url 'index:acceuil' %}" >
                            <img src='{% static "images/logo.png" %}' alt="csm-conseilsstrategiquesmarketingweb | Expert en analyse et développement web">
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <ul class="nav">
                            <li><a href="#"><span class="icon phone"></span><span class="first-word">Appeler</span>: (581) 624-1766</a></li>
                            <li><a href="mailto:cotecsm@globetrotter.net"><span class="icon email"></span><span class="first-word">Courriel</span>: cotecsm@globetrotter.net</a></li>
                            <!-- <li><a href="#"><span class="icon share"></span></a></li> -->
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!--Logo Row-->
        <nav class="row menu_row m0">
            <div class="container">
                <div class="row">
                    <div class="search_form_area fright">
                        <a href="mailto:demandecsm@globetrotter.net" class="col-md-8  col-sm-12 free_analysis ">
                            <img src='{% static "images/icons/menu/free_analysis.png" %}' alt=""> Demander une analyse
                        </a>
                    </div> <!--Search And Analysis-->
                    <div class="fleft menu_area">
                        <button class="btn btn-primary visible-xs" type="button" data-toggle="collapse" data-target="#mainMenu" aria-expanded="false" aria-controls="mainMenu">
                            <i class="glyphicon glyphicon-th-large"></i> Menu
                        </button>
                        <div class="collapse navbar-collapse" id="mainMenu">
                            <ul class="nav navbar-nav">
                                <li><a href='{% url "index:acceuil" %}'>Accueil</a></li>    
                                <li><a href="{% url "entreprise:details" %}">Entreprise</a></li>   
                                <li class="dropdown">
                                    <a href='{% url "services:liste" %}' class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Services</a>
                                    <ul class="dropdown-menu">                                   
                                        <li><a href='{% url "services:audit_web" %}'>Audit Web</a></li>
                                        <li><a href='{% url "services:seo" %}'>Services SEO</a></li>
                                        <li><a href='{% url "services:medias_sociaux" %}'>Médias sociaux</a></li>
                                        <li><a href='{% url "services:courriels" %}'>Campagnes courriels</a></li>
                                        <li><a href='{% url "services:developpement_web" %}'>Développement Web</a></li>
                                        <li><a href='{% url "services:cms" %}'>Plateformes CMS</a></li>
                                    </ul>
                                </li>   
                                 <li><a href='{% url "coaching:details" %}'>Coaching</a></li>                          
                                <li><a href='{% url "blogue:liste" %}'>Blogue</a></li>
                                <li><a href='{% url "contact:details" %}'>contact</a></li>                             
                            </ul>
                        </div>
                    </div> <!--Menu Area-->
                </div>
            </div>
        </nav> <!--Menu Row-->
    </header>

src/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %} 
{{ form.media }}

{% endblock head_extra %}



{% block content %}
<div class='col-sm-6'>
<h1>Preview</h1>
<hr/>
<div class='content-preview'>
    <h3 id='preview-title'></h3>
    <p id='preview-content'></p>
</div>
</div>
<div class='col-sm-6'>
<h1>Form</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>
</div>
{% endblock content %}