src/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
   
    url(r'^$', include("accueil.urls", namespace='index')),

    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^blogue/', include("blogue.urls", namespace='blogue')),
    url(r'^contact/', include("contact.urls", namespace='contact')),
    url(r'^entreprise/', include("entreprise.urls", namespace='entreprise')),
    url(r'^services/', include("services.urls", namespace='services')),
    url(r'^accompagnement-personnalise/', include("coaching.urls", namespace='coaching')),
 
    


    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^posts/', include("posts.urls", namespace='posts')),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blogue/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	blogue_list,
	blogue_details,
	)

urlpatterns = [
	url(r'^$', blogue_list, name='liste'),
	url(r'^article$', blogue_details, name='details'),
]

src/blogue/models.py
from django.db import models

# Create your models here.

src/blogue/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except: 
    pass
    from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render, get_object_or_404

#from .forms import CommentForm
#from .models import Comment

def blogue_list(request):
	today = timezone.now().date()

	context = {
	"title": "Blogue",
	"today": today,
	"page_active": "Nos articles",
	}
	return render(request, "blogue/liste.html", context)

def blogue_details(request):
	today = timezone.now().date()

	context = {
	"title": "Titre de l'article",
	"today": today,
	"page_active": "Titre de l'article",
	}
	return render(request, "blogue/article.html", context)

src/blogue/templates/blogue/article.html
{% extends "base.html" %}
{% load staticfiles %}

{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
    {{ instance.title }} {{ title }}{{ block.super }}
{% endblock head_title %}


{% block content %}

{% include 'couverture.html' %}
  <section class="row contentRow">
        <div class="container">
            <div class="row page_blog">
                <div class="col-sm-9 blog_sec">
                    <div class="row blog single_post m0">
                        <div class="row m0 image">
                            <img src='{% static "images/blog/1.jpg" %}' alt="">
                        </div>
                        <div class="media">
                            <div class="media-left post_cat">
                                <a href="#"><img src='{% static "images/icons/blog/4.png" %}' alt=""></a>
                            </div>
                            <div class="media-body">
                                <div class="row m0 post_meta">
                                    <div class="fleft date"><img src='{% static "images/icons/blog/1.png" %}' alt=""><a href="single-post.html">01 Sept 2016</a></div>
                                    <div class="fleft comment"><img src='{% static "images/icons/blog/2.png" %}' alt=""><a href="single-post.html#comments">5 Commentaires</a></div>
                                    <div class="fleft author"><img src='{% static "images/icons/blog/3.png" %}' alt=""><a href="#">Par Prénom Nom</a></div>
                                </div>
                                <a href="single-post.html" class="post_title">
                                    <h5>Titre de l'article</h5>
                                </a>
                            </div>
                        </div>
                        <div class="row m0 post_content">
                            <p>Nolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utalas aliquip exeap quat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eus sola fugiat nulla pariatu cpida non numquam thas dolorem ipsum quialas  perspiciatis unde omnis istem natus error sit voluptatem accus antiumu doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beateta vitae dicta sunt explicabo.</p>
                            <blockquote>Nemo enim ipsam voluptatm quiau voluptas sdite asper natureu aut odit aut fugit thamana 
consequun tur magn dolores eosope qui nisa rovasa ehenderi tione.</blockquote>
                            <p>Minim veniam, quis nostrud exercitation ullamco laboris nisi utalas aliquip exeap quat Duis aute irure dolor in repr henderit in voluptate velit esse cillum dolore eus sola fugiat nulla pariatu cupidar nonas numquam thasol dolorems
quialas  perspiciatis unde omnis istem natus error sit voluptatem accu santium.</p>
                            <p>Doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis ethis quasi architecto beat aes vitae dicta sunt explicabo Nemo enim ipsam voluptatem quia voluptas sitamet aspernatur aut odit aut fugit, sed  quiav consequuntur magni dolores eos qui ratione voluptatem sequir nesciunt. Neque porro quisquam est, qui dola lorem sola ipsum quia dolor sit amet, consectetur, adipisci sola velit, sed quia non numquam eius modi tem poramo incidunt ut labor et dolore magnam aliquam quaerat voluptatem.</p>
                        </div>
                    </div>                    
                    <div class="row m0 shares">
                        <div class="fleft share_count">15 partages</div>
                        <ul class="fright share_icon list-inline">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-rss"></i></a></li>
                        </ul>
                    </div>
                    <nav class="paginations">
                        <ul class="pager">
                            <li class="previous"><a href="#"><img src='{% static "images/icons/blog/arrow-prev.png" %}' alt=""> Précédent</a></li>
                            <li class="next"><a href="#">Suivant <img src='{% static "images/icons/blog/arrow-next.png" %}' alt=""></a></li>
                        </ul>
                    </nav>
                    <div class="row m0 comments" id="comments">
                        <h4 class="comment_count">Commentaires (3)</h4>
                        <div class="media comment">
                            <div class="media-left"><a href="#"><img src='{% static "images/blog/author1.png" %}' alt=""></a></div>
                            <div class="media-body">
                                <div class="row m0">
                                    <a href="#" class="author_name fleft">Francis Campbell</a>
                                    <a href="#reply" class="reply fright">Répondre <i class="fa fa-long-arrow-down"></i></a>
                                    <a href="#" class="date fright">01 Sept, 2016</a>
                                </div>
                                <p>Accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo marvl inven tore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                            </div>
                        </div>
                        <div class="media reply_comment comment">
                            <div class="media-left"><a href="#"><img src='{% static "images/blog/author1.png" %}' alt=""></a></div>
                            <div class="media-body">
                                <div class="row m0">
                                    <a href="#" class="author_name fleft">Francis Campbell</a>
                                    <a href="#reply" class="reply fright">Répondre <i class="fa fa-long-arrow-down"></i></a>
                                    <a href="#" class="date fright">01 Sept, 2016</a>
                                </div>
                                <p>Accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo marvl inven tore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                            </div>
                        </div>
                        <div class="media comment">
                            <div class="media-left"><a href="#"><img src='{% static "images/blog/author1.png" %}' alt=""></a></div>
                            <div class="media-body">
                                <div class="row m0">
                                    <a href="#" class="author_name fleft">Francis Campbell</a>
                                    <a href="#reply" class="reply fright">Répondre <i class="fa fa-long-arrow-down"></i></a>
                                    <a href="#" class="date fright">01 Sept, 2016</a>
                                </div>
                                <p>Accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo marvl inven tore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                            </div>
                        </div>
                    </div>
                    <h4 class="comment_leave_title page_title">Laisser un commentaire</h4>
                    <form action="#" class="row comment_form">
                        <div class="col-sm-6">
                            <div class="row m0">
                                <label for="name">Nom <span>*</span></label>
                                <input type="text" class="form-control" required id="name">
                            </div>
                            <div class="row m0">
                                <label for="email">Courriel <span>*</span></label>
                                <input type="email" class="form-control" required id="email">
                            </div>
                            <div class="row m0">
                                <label for="phone">Téléphone <span>*</span></label>
                                <input type="tel" class="form-control" required id="phone">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="row m0">
                                <label for="comments_form">Commentaire</label>
                                <textarea required class="form-control" id="comments_form"></textarea>
                            </div>
                            <input type="submit" class="form-control submit_btn" value="Envoyer">
                        </div>
                    </form>
                </div>
                <div class="col-sm-3 sidebar">
                    <form action="#" class="row search_form widget">
                        <div class="input-group">
                            <input type="search" class="form-control" placeholder="Chercher un article...">
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                        </div>
                    </form>
                    <div class="widget row post_cats">
                        <h4 class="widget_title">Catégories</h4>
                        <ul class="nav post_cat">
                            <li><a href="#">SEO</a></li>
                            <li><a href="#">Programmation Web</a></li>
                            <li><a href="#">Médias sociaux</a></li>
                            <li><a href="#">Email marketing</a></li>
                            <li><a href="#">Nouvelles technologies</a></li>
                            <li><a href="#">Marketing numérique</a></li>
                        </ul>
                    </div>
                    <div class="widget row recent_posts">
                        <h4 class="widget_title">Articles récents</h4>
                        <div class="media-group">
                            <div class="row m0 recent_post">
                                <div class="fleft links">
                                    <a href="single-post.html" class="post_title">Titre de l'article</a><br>
                                    <a href="single-post.html" class="post_meta">29 août, 2016</a>
                                </div>
                                <div class="fleft post_img">
                                    <a href="#"><img src='{% static "images/blog/recent/1.jpg" %}' alt=""></a>                           
                                </div>
                            </div> <!--Recent Post-->
                            <div class="row m0 recent_post">
                                <div class="fleft links">
                                    <a href="single-post.html" class="post_title">Titre de l'article</a><br>
                                    <a href="single-post.html" class="post_meta">29 août, 2016</a>
                                </div>
                                <div class="fleft post_img">
                                    <a href="#"><img src='{% static "images/blog/recent/2.jpg" %}' alt=""></a>                           
                                </div>
                            </div> <!--Recent Post-->
                            <div class="row m0 recent_post">
                                <div class="fleft links">
                                    <a href="single-post.html" class="post_title">Titre de l'article</a><br>
                                    <a href="single-post.html" class="post_meta">29 août, 2016</a>
                                </div>
                                <div class="fleft post_img">
                                    <a href="#"><img src='{% static "images/blog/recent/3.jpg" %}' alt=""></a>                           
                                </div>
                            </div> <!--Recent Post-->
                        </div>
                    </div>                    
                    <div class="widget row post_cats">
                        <h4 class="widget_title">Archives</h4>
                        <ul class="nav post_cat">
                            <li><a href="#">Août 2016 (4)</a></li>
                            <li><a href="#">Juillet 2016 (5)</a></li>
                            <li><a href="#">Juin 2016 (6)</a></li>
                            <li><a href="#">Mai 2016 (8)</a></li>
                        </ul>
                    </div>                   
                    <div class="widget row top_tags">
                        <h4 class="widget_title">Mots clés</h4>
                        <a href="#">Installation</a>
                        <a href="#">Croissance</a>
                        <a href="#">Stratégie</a>
                        <a href="#">Marketing</a>
                        <a href="#">Programmation</a>
                        <a href="#">SEO</a>
                        <a href="#">Sites Web</a>
                        <a href="#">Mots clés</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

src/blogue/templates/blogue/liste.html
{% extends "base.html" %}
{% load staticfiles %}

{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
	{{ instance.title }} {{ title }}{{ block.super }}
{% endblock head_title %}


{% block content %}

{% include 'couverture.html' %}
  <section class="row contentRow">
        <div class="container">
            <div class="row page_blog">
                <div class="col-sm-9 blog_sec">
                    <div class="row blog m0">
                        <div class="row m0 image">
                            <img src='{% static "images/blog/1.jpg" %}' alt="">
                        </div>
                        <div class="media">
                            <div class="media-left post_cat">
                                <a href="#"><img src='{% static "images/icons/blog/4.png" %}' alt=""></a>
                            </div>
                            <div class="media-body">
                                <div class="row m0 post_meta">
                                    <div class="fleft date"><img src='{% static "images/icons/blog/1.png" %}' alt=""><a href="single-post.html">01 Sept 2016</a></div>
                                    <div class="fleft comment"><img src='{% static "images/icons/blog/2.png" %}' alt=""><a href="single-post.html#comments">5 Commentaires</a></div>
                                    <div class="fleft author"><img src='{% static "images/icons/blog/3.png" %}' alt=""><a href="#">Par Prénom Nom</a></div>
                                </div>
                                <a href="single-post.html" class="post_title">
                                    <h5>Titre de l'article</h5>
                                </a>
                                <p class="post_text">Nolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utal aliquip exeap quat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eus fugiat nulla pariatu cupidar non numquam thas dolorem ipsum quialas[...]</p>
                                <a href="{% url 'blogue:details' %}" class="read_more">Lire la suite</a>
                            </div>
                        </div>
                    </div>
                    <div class="row blog m0">
                        <div class="row m0 image">
                            <img src='{% static "images/blog/1.jpg" %}' alt="">
                        </div>
                        <div class="media">
                            <div class="media-left post_cat">
                                <a href="#"><img src='{% static "images/icons/blog/4.png" %}' alt=""></a>
                            </div>
                            <div class="media-body">
                                <div class="row m0 post_meta">
                                    <div class="fleft date"><img src='{% static "images/icons/blog/1.png" %}' alt=""><a href="single-post.html">01 Sept 2016</a></div>
                                    <div class="fleft comment"><img src='{% static "images/icons/blog/2.png" %}' alt=""><a href="single-post.html#comments">5 Commentaires</a></div>
                                    <div class="fleft author"><img src='{% static "images/icons/blog/3.png" %}' alt=""><a href="#">Par Prénom Nom</a></div>
                                </div>
                                <a href="single-post.html" class="post_title">
                                    <h5>Titre de l'article</h5>
                                </a>
                                <p class="post_text">Nolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utal aliquip exeap quat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eus fugiat nulla pariatu cupidar non numquam thas dolorem ipsum quialas[...]</p>
                                <a href="single-post.html" class="read_more">Lire la suite</a>
                            </div>
                        </div>
                    </div>
                    <div class="row blog m0 quoteBlog">
                        <div class="quote row m0">Mullamco laboris nisi ut aliquip ex ea commtodo consequat Duost aute irure dolor in repen derit voluptate velit esse cillum dolore eu fugiat nulla pariatur</div>
                        <a href="#" class="quote_writer">&mdash; Francis Campbell</a>
                    </div>
                    <div class="row blog m0">
                        <div class="row m0 image">
                            <img src='{% static "images/blog/1.jpg" %}' alt="">
                        </div>
                        <div class="media">
                            <div class="media-left post_cat">
                                <a href="#"><img src='{% static "images/icons/blog/4.png" %}' alt=""></a>
                            </div>
                            <div class="media-body">
                                <div class="row m0 post_meta">
                                    <div class="fleft date"><img src='{% static "images/icons/blog/1.png" %}' alt=""><a href="single-post.html">01 Sept 2016</a></div>
                                    <div class="fleft comment"><img src='{% static "images/icons/blog/2.png" %}' alt=""><a href="single-post.html#comments">5 Commentaires</a></div>
                                    <div class="fleft author"><img src='{% static "images/icons/blog/3.png" %}' alt=""><a href="#">Par Prénom Nom</a></div>
                                </div>
                                <a href="single-post.html" class="post_title">
                                    <h5>Titre de l'article</h5>
                                </a>
                                <p class="post_text">Nolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utal aliquip exeap quat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eus fugiat nulla pariatu cupidar non numquam thas dolorem ipsum quialas[...]</p>
                                <a href="single-post.html" class="read_more">Lire la suite</a>
                            </div>
                        </div>
                    </div>
                    <div class="row pagination m0">
                        <ul class="list-inline">
                            <li>pages</li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li>...</li>
                            <li><a href="#">20</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 sidebar">
                    <form action="#" class="row search_form widget">
                        <div class="input-group">
                            <input type="search" class="form-control" placeholder="Chercher un article...">
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                        </div>
                    </form>
                    <div class="widget row post_cats">
                        <h4 class="widget_title">Catégories</h4>
                        <ul class="nav post_cat">
                            <li><a href="#">SEO</a></li>
                            <li><a href="#">Programmation Web</a></li>
                            <li><a href="#">Médias sociaux</a></li>
                            <li><a href="#">Email marketing</a></li>
                            <li><a href="#">Nouvelles technologies</a></li>
                            <li><a href="#">Marketing numérique</a></li>
                        </ul>
                    </div>
                    <div class="widget row recent_posts">
                        <h4 class="widget_title">Articles récents</h4>
                        <div class="media-group">
                            <div class="row m0 recent_post">
                                <div class="fleft links">
                                    <a href="single-post.html" class="post_title">Titre de l'article</a><br>
                                    <a href="single-post.html" class="post_meta">29 août, 2016</a>
                                </div>
                                <div class="fleft post_img">
                                    <a href="#"><img src='{% static "images/blog/recent/1.jpg" %}' alt=""></a>                           
                                </div>
                            </div> <!--Recent Post-->
                            <div class="row m0 recent_post">
                                <div class="fleft links">
                                    <a href="single-post.html" class="post_title">Titre de l'article</a><br>
                                    <a href="single-post.html" class="post_meta">29 août, 2016</a>
                                </div>
                                <div class="fleft post_img">
                                    <a href="#"><img src='{% static "images/blog/recent/2.jpg" %}' alt=""></a>                           
                                </div>
                            </div> <!--Recent Post-->
                            <div class="row m0 recent_post">
                                <div class="fleft links">
                                    <a href="single-post.html" class="post_title">Titre de l'article</a><br>
                                    <a href="single-post.html" class="post_meta">29 août, 2016</a>
                                </div>
                                <div class="fleft post_img">
                                    <a href="#"><img src='{% static "images/blog/recent/3.jpg" %}' alt=""></a>                           
                                </div>
                            </div> <!--Recent Post-->
                        </div>
                    </div>                    
                    <div class="widget row post_cats">
                        <h4 class="widget_title">Archives</h4>
                        <ul class="nav post_cat">
                            <li><a href="#">Août 2016 (4)</a></li>
                            <li><a href="#">Juillet 2016 (5)</a></li>
                            <li><a href="#">Juin 2016 (6)</a></li>
                            <li><a href="#">Mai 2016 (8)</a></li>
                        </ul>
                    </div>                   
                    <div class="widget row top_tags">
                        <h4 class="widget_title">Mots clés</h4>
                        <a href="#">Installation</a>
                        <a href="#">Croissance</a>
                        <a href="#">Stratégie</a>
                        <a href="#">Marketing</a>
                        <a href="#">Programmation</a>
                        <a href="#">SEO</a>
                        <a href="#">Sites Web</a>
                        <a href="#">Mots clés</a>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock content %}